name: Registryswarm CI

on:
  release:
    types: [created]

env:
  IMAGE_NAME: registryswarm

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to dockr.it
        uses: docker/login-action@v2
        with:
          registry: dockr.it
          username: ${{ secrets.DOCKRIT_USER }}
          password: ${{ secrets.DOCKRIT_PASS }}

      - name: Build and push to dockr.it (x86_64) with version tag
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            dockr.it/${{ env.IMAGE_NAME }}:latest
            dockr.it/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          platforms: linux/amd64

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to ghcr.io (multi-platform) with version tag
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ghcr.io/stenstromen/${{ env.IMAGE_NAME }}:latest
            ghcr.io/stenstromen/${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}
          platforms: linux/amd64,linux/arm64
